export const guests: Record<string, string[]> = {
  "vovo-eliana": ["Vovó Eliana", "Vovô Nené"],
  "tio-cezar": ["Tio Cezar", "Tia Karol", "Noah"],
  "tia-deda": ["Tia Deda", "Tio Tamiro", "Juju"],
  "tia-preta": ["Tia Preta", "Tio Lô", "Enzinho"],
  "tio-bigode": ["Tio Bigode", "Tia Regina"],
  fran: ["Fran", "Uilliam", "Yago", "Laís"],
  "tio-siva": ["Tio Siva", "Tia Simoni"],
  "vovo-zuleide": ["Vovó Zuleide"],
  "tia-vaninha": ["Tia Vaninha", "Tio Teu"],
  "tia-tinha": ["Tia Tinha", "Tio Lolô"],
  natalia: ["Natália", "Quénia"],
  juliano: ["Juliano", "Giuliana"],
  felipe: ["Felipe", "Juliana"],
  "vovo-diana": ["Vovó Diana", "Vovô Evandro", "Tia Lelê"],
  "vovo-neuza": ["Vovó Neuza"],
  "tia-monica": ["Tia Mônica", "Tio Oda", "Emanuel"],
  davi: ["Davi", "Duda"],
  "tio-heber": ["Tio Héber", "Tia Lurdes", "Bel", "Enzo"],
  adriano: ["Adriano", "Keila", "Anne"],
  "ana-lucia": ["Ana Lúcia", "Evelyn", "Danillo"],
  "tia-luiza": ["Tia Luiza", "Tio Euzébio"],
  priscila: ["Priscila", "Gilmar", "Lorenzo"],
  george: ["George", "Missiana", "Samuel", "Rafael"],
  cristiano: ["Cristiano"],
  beth: ["Beth", "Vitinho", "Kamilly"],
  naiady: ["Naiady", "Romério", "Emily", "Cecília"],
  "tia-pia": ["Tia Pia"],
  saiani: ["Saiani", "Jefin", "Arthur", "Pedro José"],
  danilo: ["Danilo", "Amanda", "Ben"],
  "tia-karol": ["Tia Karol"],
  "tia-ana": ["Tia Paulinha"],
  eliana: ["Eliana", "Dirceu", "Gabriel"],
  junior: ["Júnior", "Camila"],
  bisa: ["Bisa Ida", "Tia Gorete"],
  asthar: ["Asthar", "Maiara", "Haim"],
  teresa: ["Teresa", "Geraldo"],
  jeniffer: ["Jeniffer", "Carlos Henrique", "Bernardo"],
};
